### ISSUE TITLE
cds's readlink is not supported on all systems

### ISSUE THREAD

**Issue by aryam7** [GiselleSerate/myaliases#19]
The `readlink` command, which `cds` uses to get the absolute, target path for a symlink, is not supported on all systems, especially Macs. It apparently doesn't have good alternatives.

**Comment by aryam7** [comment]
<h2>Things we can do:</h2>
- implement our own version of `readlink` and stick it in the .bash_cds file. this could be copy-pasted from the internet
- use python's version of real_path
- come up with some other way of getting the absolute, target path of `cds`'s symlinks

**Comment by GiselleSerate** [comment]
I think I also use this in my install script, so this is something we should consider handling.

**Comment by GiselleSerate** [comment]
For posterity (meaning us in about a week, probably): 
We're using a C realpath method. (Executable included in repo so users don't have to do stuff.)

**Comment by aryam7** [comment]
Do we see ourselves ever needing the C code? What are your feelings about keeping it?

**Comment by aryam7** [comment]
Also, currently realpath is called using ./realpath notation. However, this allows realpath to only be called from executables in the same directory as realpath (ie the cds command can't call it).
Maybe we could create an alias function for realpath in .cds_nav? Would that solve the problem?

**Comment by aryam7** [comment]
For posterity, our current plan is to use setup to create a variable accessible to all files that are included by .included. This variable would hold a string representing the path to the repository directory.
Then, all of the other files in the repository could use this variable directly or use it to call realpath.
See issue #25.
