### ISSUE TITLE
what do you do if the alias already exists? oh noes

### ISSUE THREAD

**Issue by GiselleSerate** [GiselleSerate/myaliases#38]
It's easy for the aliases in the file we wrote. What about other aliases? I think the alias command would be helpful here, but parsing might be sketchy.

**Comment by GiselleSerate** [comment]
Create a temp file, pipe in the output from the `alias` command and grep through it for `alias \""$1"` at the beginning of each line?

**Comment by aryam7** [comment]
Maybe [this](https://stackoverflow.com/questions/9783507/how-can-i-check-in-my-bashrc-if-an-alias-was-already-set) will help?
It says you can use the `unalias` command.

**Comment by GiselleSerate** [comment]
I reverse engineered this basically xD thanks though, useful suggestions

**Comment by GiselleSerate** [comment]
Most relevantly: what should the behavior be in this edge case? Should we:

- unalias the old command and set the new command? (If so, should we do this explicitly with an unalias in the generated file or silently override it?)
- check if we set the old command in our generated file and delete that line? Is this even a desired behavior?
- reject the new command?

**Comment by aryam7** [comment]
Since this command is all about convenience, I would have it override the old alias and not reject the new command. I would also check the generated file and delete, if necessary. I'm also generally a fan of doing things silently, but we could echo out a statement telling the user that they're old alias has been overridden. However, you might only want to do that when it's from our generated file so that we can stay true to the original behavior of `alias`?

**Comment by GiselleSerate** [comment]
Oooh, that sounds like a great way to handle it. Currently I have it failing verbosely, but that shouldn't be terrible to implement.

**Comment by GiselleSerate** [comment]
Currently deletes the old alias silently from `.usr_aliases` and does nothing otherwise. 
This seems to work for for all cases quite well; I'd probably only be worried about order if they try to override a name that someone is already using. Because then inclusion in how things get called from the `.bashrc` matters a lot as far as what actually gets defined.

**Comment by GiselleSerate** [comment]
This happens when I leave projects for a long time; I forget why I haven't closed issues. I'm going to close this, because my previous comments sound pretty resolvey to me?
