### ISSUE TITLE
clangpl is having a fit

### ISSUE THREAD

**Issue by GiselleSerate** [GiselleSerate/myaliases#4]
Seems like there's some confusion with argument order. Check on this.

**Comment by aryam7** [comment]
What are the steps to reproduce the bug?

**Comment by GiselleSerate** [comment]
I'm not entirely sure why this worked; I ran it once and it couldn't find the .o file, then I ran it again and it worked perfectly. I've got some local changes brewing, but I'll try to reset the folder I was compiling in and try again.

**Comment by GiselleSerate** [comment]
Error messages: (I echoed some stuff out that I don't remember if I've pushed? but that's what all the extra messages are.) For reference, I'm using try3 from the CS70 code. 
$ clangpl countdown printvector
clang++ -c -o countdown.o -std=c++11 -pedantic -Wall -Wextra countdown.cpp
clang: error: no such file or directory: 'printvector.o'
clang++ -o countdown countdown.o printvector.o
./countdown
