### ISSUE TITLE
desk is broken

### ISSUE THREAD

**Issue by GiselleSerate** [GiselleSerate/myaliases#42]
like it no longer works
I mean, presumably it's been made obsolete by cds but we should really do something about it.

**Comment by GiselleSerate** [comment]
Did they update bash and change stuff? All my normal symlinks are broken.
![image](https://user-images.githubusercontent.com/13649793/34539467-6b24d784-f085-11e7-8af5-208bace5a113.png)

**Comment by aryam7** [comment]
woah umm idk
`desk` is still working for me, I think

But maybe I should check for Windows updates?

**Comment by GiselleSerate** [comment]
I've never had those errors when `ls`ing in any directory. 
My error when I try to run `desk` is: 
`-bash: cd: /mnt/c/Users/User/Desktop: No such file or directory`
Which is kind of weird, and I thought was maybe associated with the broken symlinks, but I couldn't be sure.

**Comment by aryam7** [comment]
Wait - does it actually say `/mnt/c/Users/User/Desktop` or does it say something like `/mnt/c/Users/gsera/Desktop`?
What gets printed when you run `cmd "echo %USERNAME%"`?

**Comment by GiselleSerate** [comment]
It says `User` in the filepath. It also prints `User` for the command you have written in the script currently (which I tried). 
`cmd "echo %Username%"` gives `User`
`cmd whoami` gives `gisellelaptop\user`
`cmd "echo %USERPROFILE%"` gives `C:\Users\gsera`
