### ISSUE TITLE
sanitize nickname input

### ISSUE THREAD

**Issue by GiselleSerate** [GiselleSerate/myaliases#47]
Currently I'm leaving the input checking very basic; you just can't use special characters. I think some of them are permissible in alias, though, so you should:
- [x] figure out which characters are okay in alias
- [x] add the above to the permissible character set

**Comment by GiselleSerate** [comment]
- `@`, `#`, `^`, `*`, `-`, `_`, `+`, `,`, `.`, `?`, `{`, `}`, `[`, `]` get saved. Permissible characters. **Don't remove these.**
- `'`, `"` don't get saved, but calling the alias with quotes in it preserves behavior as long as there are matching quotes within the alias. **Can be handled if left in, or not.**
- `\` doesn't get saved, but if you call alias with `\` the line it returns can be handled properly. **Can be handled if left in, or not.**
- `!`, `&`, `(`, `)`, `=`, `/`, `:`, `;`, `<`, `>`, `|` break the normal alias command, so we can call those undefined behavior. **Don't worry about these characters.**
- `$` substitutes in the variable that bash thinks follows $. **This is a problem.**

Strategy: stop sanitizing, it's fine. The only problem is substituting in variable names.

**Comment by aryam7** [comment]
And alias doesn't allow $ signs in their alias names, I think.
"The characters `/`, `$`, \`, `=` and any of the shell metacharacters or quoting characters listed above may not appear in an alias name." (according to the [manual](https://www.gnu.org/software/bash/manual/bash.html#Aliases)?)
So `alias 'hi$bro'='desk'` won't work.

**Comment by GiselleSerate** [comment]
Yeah, I think the only thing that we might need to worry about are variable substitutions.
