### ISSUE TITLE
Move clangd functionality to clangl

### ISSUE THREAD

**Issue by aryam7** [GiselleSerate/myaliases#6]
clangl should have the functionality of clangd on request, so that if somebody compiles object files with clangp and then wants to link with clangl, they can still have the option to delete all files afterward.
Ideally, this would be done with options, but that gets a bit tricky...

**Comment by aryam7** [comment]
this could be made a lot easier if we implemented the functionality of issue #9

**Comment by GiselleSerate** [comment]
(Because we discovered Makefiles.)
