### ISSUE TITLE
typeset?

### ISSUE THREAD

**Issue by GiselleSerate** [GiselleSerate/myaliases#63]
https://github.com/GiselleSerate/myaliases/wiki/.bash_alias

@aryam7 I noticed you had typeset in aliasing `cd` to `cds`. I threw it in my page on `.bash_alias` but I'm not actually sure why you had that?

**Comment by aryam7** [comment]
I don't remember all that well, but I think it was the best way I could find to make sure that cds had been appropriately defined before performing the aliasing.

**Comment by GiselleSerate** [comment]
Well that sounds useful for altalias. I'll leave it as is then. Thanks!
