### ISSUE TITLE
cds tab complete shell conditional agh

### ISSUE THREAD

**Issue by aryam7** [GiselleSerate/myaliases#68]
In order to prevent `.bash_cds` from attempting to register cds tab completions in a shell that is unsupported, I check `$BASH_VERSION` to see whether the current shell is bash (and not zsh, for example, which uses a different completion system).

Unfortunately, this has disabled cds tab completion on some bash systems. Fix the conditional so that it can better detect which shell you're using. Maybe also look at the setup script because we had to do this back then, right?

**Comment by aryam7** [comment]
[this way](https://unix.stackexchange.com/questions/96305/which-shell-am-i-running-on) seems pretty portable

**Comment by aryarm** [comment]
Looking back on this issue, I'm not really sure why I said that the old method would disable tab completion on some bash systems. In fact, the old method was actually more portable. For example, the old method works on BusyBox while the new method doesn't.
In any case, I revert to the old method in 38c86ea.
