### ISSUE TITLE
Add clangd option to not delete executable

### ISSUE THREAD

**Issue by aryam7** [GiselleSerate/myaliases#7]
The executable might be useful for later use. Maybe the developer wants to test their executable with different parameters several times, for example.

**Comment by aryam7** [comment]
This functionality was completed in https://github.com/GiselleSerate/myaliases/commit/34c1c475e52dcdb50ee1af18a369664cbc66c1ce

**Comment by GiselleSerate** [comment]
(Because we discovered Makefiles.)
