### ISSUE TITLE
Setup script's jank on an RPI

### ISSUE THREAD

**Issue by GiselleSerate** [GiselleSerate/myaliases#79]
Tried it, had problems with realpath. Maybe should recompile. 
Yep, need to recompile. Please write a Makefile.

**Comment by GiselleSerate** [comment]
...Everything's borked on the Pi. Well. Can't cds, can't src.

**Comment by GiselleSerate** [comment]
I'm running Raspbian.

**Comment by GiselleSerate** [comment]
EDIT: nope it's fine, just gotta do that Makefile because if it can't use realpath it does some real jank stuff and doesn't compensate for it not being there.

**Comment by aryam7** [comment]
oh boy. So it just goes back to #33 
Yeah, I was reading that Debian has its own version of realpath too
But that it's version isn't consistent with other implementations of realpath 😥

**Comment by GiselleSerate** [comment]
Closing, moving discussion to #33.
