### ISSUE TITLE
add option for verbose vs quite

### ISSUE THREAD

**Issue by aryam7** [GiselleSerate/myaliases#8]
It might be nice if all functions didn't output the commands they were running by default. This would allow the developer to quickly see the output that is important (from his/her own code) rather than having to visually pick it out.
Perhaps the best way to do this is to add the option -v (for "verbose") to every function?

**Comment by aryam7** [comment]
this could work really easily if we do #9

**Comment by GiselleSerate** [comment]
(Because we discovered Makefiles.)
